# Generated by Django 3.2.5 on 2021-07-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_auto_20210715_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
